# roles/system_preferences/handlers/main.yml

- name: restart Dock
  command: killall Dock

- name: restart Finder
  command: killall cfprefsd && killall Finder

- name: restart SystemUIServer
  command: killall SystemUIServer
