# roles/system_preferences/tasks/main.yml

# Desktop and Wallpaper
- name: Set Desktop wallpaper to black
  command: osascript -e 'tell application "System Events" to set picture of every desktop to "/System/Library/Desktop Pictures/Solid Colors/Black.png"'
  become: true
  become_user: "{{ ansible_facts['user_id'] }}"
  tags: system_preferences
  notify: restart Dock

# Dock Settings
- name: Set Dock to auto-hide
  command: defaults write com.apple.dock autohide -bool true
  notify: restart Dock

- name: Set Dock position to left
  command: defaults write com.apple.dock orientation -string "left"
  notify: restart Dock

- name: Set Dock animation speed
  command: defaults write com.apple.dock autohide-time-modifier -float 0.5
  notify: restart Dock

- name: Set Dock tile size
  command: defaults write com.apple.dock tilesize -int 32
  notify: restart Dock

- name: Enable Dock magnification
  command: defaults write com.apple.dock magnification -bool true
  notify: restart Dock

- name: Set Dock magnification size
  command: defaults write com.apple.dock largesize -int 64
  notify: restart Dock

# Finder Settings
- name: Do not show hidden files in Finder
  command: defaults write com.apple.finder AppleShowAllFiles -bool false
  notify: restart Finder

- name: Hide all file extensions in Finder
  command: defaults write NSGlobalDomain AppleShowAllExtensions -bool false
  notify: restart Finder

- name: Set Finder default location to home
  command: defaults write com.apple.finder NewWindowTarget -string "PfHm"
  notify: restart Finder

- name: Show path bar in Finder
  command: defaults write com.apple.finder ShowPathbar -bool true
  notify: restart Finder

- name: Set default Finder view to Column view
  command: defaults write com.apple.finder FXPreferredViewStyle -string "clmv"
  notify: restart Finder

- name: Disable recent tags in Finder sidebar
  command: defaults write com.apple.finder ShowRecentTags -bool false
  notify: restart Finder

- name: Sort folders before files in Finder
  command: defaults write com.apple.finder _FXSortFoldersFirst -bool true
  notify: restart Finder

- name: Hide disks on Desktop
  command: defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false
  notify: restart Finder

- name: Status Path Bar starts at HOME
  command: defaults write /Library/Preferences/com.apple.finder PathBarRootAtHome -bool true
  become: true
  notify: restart Finder

# Date & Time Settings
- name: Set time format to 24-hour
  command: defaults write NSGlobalDomain AppleICUForce24HourTime -bool true
  notify: restart SystemUIServer

# Disable Metadata Creation
- name: Disable creation of metadata files on USB Volumes
  command: defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
  notify: restart Finder

- name: Disable creation of metadata files on Network Volumes
  command: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
  notify: restart Finder

# Disable Special Character on KeyHold
- name: Turn off small popup menu showing accent characters
  command: defaults write -g ApplePressAndHoldEnabled -bool false
  notify: restart SystemUIServer

# Close Printer App when printing completes
- name: Close Printer App
  command: defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true
  notify: restart Finder

# Mail
- name: Windows Friendly Attachments
  command: defaults write com.apple.mail SendWindowsFriendlyAttachments -bool true

# Screenshots
- name: Enable drop shadow on screenshots
  command: defaults write com.apple.screencapture disable-shadow -bool false